Class {
	#name : #PCPPReference,
	#superclass : #PCPPObject,
	#instVars : [
		'referenceId',
		'name',
		'id'
	],
	#category : #ProfilerCPP
}

{ #category : #'as yet unclassified' }
PCPPReference >> id [
	^ id
]

{ #category : #'as yet unclassified' }
PCPPReference >> id: anObject [
	id := anObject
]

{ #category : #'as yet unclassified' }
PCPPReference >> name [
	^ name
]

{ #category : #'as yet unclassified' }
PCPPReference >> name: anObject [
	name := anObject
]

{ #category : #'as yet unclassified' }
PCPPReference >> referenceId [
	^ referenceId
]

{ #category : #'as yet unclassified' }
PCPPReference >> referenceId: anObject [
	referenceId := anObject
]
