"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestRoassal,
	#superclass : #PackageManifest,
	#category : #Roassal2
}

{ #category : #'code-critics' }
ManifestRoassal class >> ruleRTInvocationSequenceRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#Roassal2)) #'2017-10-11T18:15:30.966581-03:00') )
]
