"
RTAnimatedScatterPlotExample new installTitle: 'EvolutionOfGraphET2' 
		code:
		'
| b |
b := RTAnimatedScatterPlot new.

b addName: ''Version 22 of GraphET2'' table: (RTTabTable new input:  ''GET2HorizontalBarDiagram	12	0	70	
GET2AbstractLineDiagram	23	5	86	
GET2AxisBuilderTest	8	0	54	
GET2UnionDiagram	8	1	26	
GET2VerticalLabelDecorator	3	0	10	
GET2RegularLabelDecorator	12	2	51	
GET2ModelLabelDecorator	8	2	31	
GTScatterplot	5	1	51	
GET2AbstractAxisBuilder	18	2	55	
GET2Abstract2DDiagram	22	4	94	
GET2SingleAxisDiagram	17	2	65	
GET2Examples	64	0	48	
GET2RegularTickDecorator	6	1	24	
GET2AbstractAxisDecorator	10	1	64	
GET2AbstractAxisStrategy	8	1	17	
GET2OrdinaryLineDiagram	7	1	40	
GET2TopDownAxisStrategy	3	0	11	
GET2AbstractBarDiagram	11	2	34	
GET2Distribution	8	1	41	
GET2InteractionWrapper	9	1	33	
GET2UnionDiagramTest	4	0	60	
GTBuilderTest	3	0	38	
GTHistogram	2	0	5	
GET2BaseLineDecorator	2	0	10	
GTAbstractBuilder	18	4	57	
GTLine	3	0	19	
GET2LineDiagram	19	3	94	
GET2DiagramBuilder	19	2	55	
GET2PieDiagramTest	2	0	22	
GET2YAxisBuilder	2	0	15	
GET2Scatterplot	7	1	38	
GET2PieDiagram	9	2	35	
GET2OldExamples	59	0	48	
GET2XAxisBuilder	2	0	15	
GET2LineDiagramTest	12	0	128	
GET2CompositeDiagramTest	16	0	240	
GET2VerticalBarDiagram	11	0	66	
GET2BarDiagramTest	34	0	525	
GET2AbstractDiagram	47	15	138	
GET2TitleDecorator	2	0	14	
GET2CompositeDiagram	18	1	70	
GET2RotatedLabelDecorator	10	1	47	
GET2Axis	29	10	71	
GET2Version	4	2	13	
DotaHero	8	4	21	
GET2LeftRightAxisStrategy	3	0	11	
GET2DataObject	8	3	24	
'').

b addName: ''Version 28 of GraphET2'' table: (RTTabTable new input: 
''GET2HorizontalBarDiagram	12	0	71	
GET2AbstractLineDiagram	21	5	82	
GET2VerticalLabelDecorator	3	0	10	
GET2UnionDiagram	8	1	26	
GET2AbstractBuilder	26	11	85	
GET2RegularLabelDecorator	12	2	51	
GET2ModelLabelDecorator	8	2	31	
GET2CatalogTest	1	0	10	
GET2AbstractAxisBuilder	29	4	85	
GET2SingleAxisDiagram	11	2	38	
GET2Examples	69	0	48	
GET2AbstractAxisBuilderTest	11	0	80	
GET2RegularTickDecorator	6	1	24	
GET2Line	10	5	44	
GET2CatalogSample	10	2	29	
GET2AbstractAxisDecorator	11	1	66	
GET2AbstractAxisStrategy	8	1	17	
GET2OrdinaryLineDiagram	8	1	43	
GET2TopDownAxisStrategy	3	0	11	
GET2AbstractBarDiagram	8	2	24	
GET2InteractionBuilder	4	2	25	
GET2Distribution	8	1	41	
GET2InteractionWrapper	9	1	33	
GET2UnionDiagramTest	4	0	60	
GTBuilderTest	3	0	38	
GET2ScatterplotDiagram	7	1	38	
GET2BaseLineDecorator	2	0	10	
GET2LineDiagram	17	3	85	
GET2DiagramBuilder	19	2	55	
GET2PieDiagramTest	2	0	22	
GET2YAxisBuilder	4	0	11	
GET2Scatterplot	5	1	51	
GET2PieDiagram	9	2	35	
GET2OldExamples	59	0	48	
GET2XAxisBuilder	4	0	11	
GET2LineDiagramTest	12	0	128	
GET2Catalog	10	1	23	
GET2CompositeDiagramTest	16	0	240	
GET2Histogram	10	2	31	
GET2VerticalBarDiagram	10	0	67	
GET2BarDiagramTest	34	0	525	
GET2AbstractDiagram	54	15	156	
GET2TitleDecorator	2	0	14	
GET2CompositeDiagram	16	1	66	
GET2RotatedLabelDecorator	10	1	47	
GET2Axis	33	10	85	
GET2Version	4	2	13	
DotaHero	8	4	21	
GET2LeftRightAxisStrategy	3	0	11	
GET2DataObject	8	3	24	
'').


b addName: ''Version 34 of GraphET2'' table: (RTTabTable new input: 
''GET2CompositeBuilder	7	1	31	
GET2HorizontalBarDiagram	12	0	72	
GET2Builder	29	11	95	
GET2AbstractLineDiagram	19	5	78	
GET2Bar	10	2	31	
GET2UnionDiagram	9	1	29	
GET2VerticalLabelDecorator	3	0	10	
GET2RegularLabelDecorator	12	2	51	
GET2ModelLabelDecorator	8	2	32	
GET2CatalogTest	1	0	10	
GET2LabelDecorator	8	0	48	
GET2SingleAxisDiagram	7	2	20	
GET2Examples	73	0	48	
GET2RegularTickDecorator	6	1	24	
GET2Line	10	5	44	
GET2CatalogSample	10	2	29	
GET2AbstractAxisDecorator	9	2	38	
GET2AbstractAxisStrategy	8	1	17	
GET2OrdinaryLineDiagram	8	1	43	
GET2TopDownAxisStrategy	3	0	11	
GET2AbstractBarDiagram	8	2	24	
GET2InteractionBuilder	4	2	25	
GET2Distribution	8	1	41	
GET2InteractionWrapper	9	1	33	
GET2UnionDiagramTest	4	0	60	
GTBuilderTest	3	0	38	
GET2UnionBuilder	5	1	17	
GET2AxisBuilder	39	7	109	
GET2AxisBuilderTest	15	0	119	
GET2LineDiagram	19	3	93	
GET2BaseLineDecorator	2	0	10	
GET2ScatterplotDiagram	7	1	38	
GET2PieDiagramTest	2	0	22	
GET2YAxisBuilder	4	0	11	
GET2Scatterplot	5	1	52	
GET2PieDiagram	9	2	37	
GET2OldExamples	60	0	48	
GET2XAxisBuilder	4	0	11	
GET2DiagramBuilder	19	2	55	
GET2LineDiagramTest	12	0	128	
GET2Catalog	10	1	23	
GET2CompositeDiagramTest	16	0	240	
GET2VerticalBarDiagram	8	0	64	
GET2BarDiagramTest	34	0	525	
GET2AbstractDiagram	67	15	193	
GET2TitleDecorator	2	0	14	
GET2CompositeDiagram	14	1	62	
GET2RotatedLabelDecorator	6	1	18	
GET2Axis	36	10	91	
GET2Version	4	2	13	
DotaHero	8	4	21	
GET2LeftRightAxisStrategy	3	0	11	
GET2DataObject	8	3	24	
'').


b addName: ''Version 38 of GraphET2'' table: (RTTabTable new input:  ''GET2LabelDecorator	1	1	7	
GET2VerticalBarDiagram	8	0	65	
GET2SingleAxisDiagram	7	2	20	
GET2PieDiagram	9	2	37	
GET2HorizontalBarDiagram	12	0	72	
GET2Line	10	5	44	
GET2NumericLabelDecorator	15	3	55	
GET2Axis	38	10	99	
DotaHero	8	4	21	
GET2LineDiagram	19	3	93	
GET2TopDownAxisStrategy	3	0	11	
GET2Scatterplot	5	1	52	
GET2XAxisBuilder	4	0	11	
GTBuilderTest	3	0	38	
GET2Bar	10	2	31	
GET2UnionDiagramTest	5	0	128	
GET2AbstractLineDiagram	19	5	78	
GET2DiagramBuilder	21	2	59	
GET2InteractionBuilder	4	2	25	
GET2AbstractBarDiagram	8	2	24	
GET2AbstractAxisDecorator	19	2	84	
GET2ObliqueLabelCreator	6	1	15	
GET2HorizontalLabelCreator	1	0	7	
GET2VerticalLabelCreator	2	0	7	
GET2Version	4	2	13	
GET2OldExamples	60	0	48	
GET2BaseLineDecorator	2	0	10	
GET2PieDiagramTest	2	0	22	
GET2LineDiagramTest	12	0	131	
GET2Catalog	10	1	23	
GET2ModelLabelDecorator	8	2	33	
GET2DataObject	8	3	24	
GET2UnionDiagram	9	1	31	
GET2BarDiagramTest	35	0	521	
GET2OrdinaryLineDiagram	8	1	43	
GET2ScatterplotDiagram	7	1	38	
GET2Builder	32	12	104	
GET2Distribution	8	1	41	
GET2AbstractAxisStrategy	8	1	17	
GET2CatalogSample	10	2	29	
GET2CompositeDiagram	14	1	64	
GET2AxisBuilder	45	9	137	
GET2YAxisBuilder	4	0	11	
GET2CompositeDiagramTest	16	0	240	
GET2AbstractDiagram	69	16	202	
GET2UnionBuilder	5	1	17	
GET2LabelCreator	6	0	7	
GET2Examples	72	0	48	
GET2RegularTickDecorator	7	1	30	
GET2InteractionWrapper	9	1	33	
GET2LeftRightAxisStrategy	3	0	11	
GET2CompositeBuilder	7	1	31	
GET2AxisBuilderTest	16	0	124	
GET2TitleDecorator	3	0	20	
'').
b addName: ''Version 42 of GraphET2'' table: (RTTabTable new input:  ''GET2LabelDecorator	1	0	7	
GET2VerticalBarDiagram	8	0	65	
GET2SingleAxisDiagram	7	2	20	
GET2PieDiagram	9	2	37	
GET2HorizontalBarDiagram	12	0	72	
GET2Line	10	5	49	
GET2CompositeBuilderTest	11	0	150	
GET2NumericLabelDecorator	14	3	53	
GET2Axis	40	10	105	
DotaHero	8	4	21	
GET2LineDiagram	19	3	93	
GET2TopDownAxisStrategy	3	0	11	
GET2Scatterplot	5	1	53	
GET2XAxisBuilder	4	0	11	
GTBuilderTest	3	0	45	
GET2Bar	10	2	31	
GET2BackgroundLinesDecorator	11	2	42	
GET2AbstractLineDiagram	19	5	78	
GET2UnionDiagramTest	5	0	128	
GET2InteractionBuilder	4	2	25	
GET2AbstractBarDiagram	8	2	24	
GET2AbstractAxisDecorator	20	4	88	
GET2ObliqueLabelCreator	6	1	15	
GET2HorizontalLabelCreator	1	0	7	
GET2VerticalLabelCreator	2	0	7	
GET2Version	4	2	13	
GET2OldExamples	60	0	48	
GET2BaseLineDecorator	2	0	10	
GET2PieDiagramTest	2	0	22	
GET2LineDiagramTest	12	0	131	
GET2Catalog	10	1	23	
GET2DiagramBuilder	21	2	59	
GET2ModelLabelDecorator	5	1	27	
GET2DataObject	8	3	24	
GET2UnionDiagram	9	1	31	
GET2BarDiagramTest	35	0	521	
GET2OrdinaryLineDiagram	8	1	43	
GET2ScatterplotDiagram	7	1	38	
GET2Builder	30	12	112	
GET2Distribution	8	1	41	
GET2AbstractAxisStrategy	8	1	17	
GET2CatalogSample	10	2	29	
GET2CompositeDiagram	14	1	65	
GET2AxisBuilder	50	11	151	
GET2YAxisBuilder	4	0	11	
GET2CompositeDiagramTest	17	0	252	
GET2AbstractDiagram	70	16	205	
GET2UnionBuilder	5	1	18	
GET2LabelCreator	6	0	7	
GET2Examples	73	0	48	
GET2RegularTickDecorator	6	1	24	
GET2InteractionWrapper	9	1	33	
GET2LeftRightAxisStrategy	3	0	11	
GET2CompositeBuilder	6	1	31	
GET2AxisBuilderTest	16	0	124	
GET2TitleDecorator	3	0	20	
'').
b addName: ''Version 45 of GraphET2'' table: (RTTabTable new input:  ''GET2LabelDecorator	1	0	7	
GET2VerticalBarDiagram	8	0	65	
GET2SingleAxisDiagram	7	2	20	
GET2PieDiagram	9	2	37	
GET2HorizontalBarDiagram	12	0	72	
GET2Line	10	5	49	
GET2CompositeBuilderTest	11	0	150	
GET2NumericLabelDecorator	18	3	90	
GET2Axis	40	10	105	
DotaHero	8	4	21	
GET2LineDiagram	19	3	93	
GET2TopDownAxisStrategy	3	0	11	
GET2Scatterplot	5	1	53	
GET2XAxisBuilder	4	0	11	
GTBuilderTest	3	0	45	
GET2Bar	10	2	37	
GET2BackgroundLinesDecorator	11	2	42	
GET2AbstractLineDiagram	19	5	78	
GET2UnionDiagramTest	5	0	128	
GET2InteractionBuilder	4	2	25	
GET2AbstractBarDiagram	8	2	24	
GET2AbstractAxisDecorator	20	4	88	
GET2ObliqueLabelCreator	6	1	15	
GET2HorizontalLabelCreator	1	0	7	
GET2VerticalLabelCreator	2	0	7	
GET2Version	4	2	13	
GET2OldExamples	60	0	48	
GET2BaseLineDecorator	2	0	10	
GET2PieDiagramTest	2	0	22	
GET2LineDiagramTest	12	0	131	
GET2Catalog	10	1	23	
GET2DiagramBuilder	21	2	59	
GET2ModelLabelDecorator	5	1	27	
GET2DataObject	8	3	24	
GET2UnionDiagram	9	1	31	
GET2BarDiagramTest	35	0	521	
GET2OrdinaryLineDiagram	8	1	43	
GET2ScatterplotDiagram	7	1	38	
GET2Builder	30	12	112	
GET2Distribution	8	1	41	
GET2AbstractAxisStrategy	8	1	17	
GET2CatalogSample	10	2	29	
GET2CompositeDiagram	14	1	65	
GET2AxisBuilder	50	11	151	
GET2YAxisBuilder	4	0	11	
GET2CompositeDiagramTest	17	0	252	
GET2AbstractDiagram	70	16	205	
GET2UnionBuilder	5	1	18	
GET2LabelCreator	6	0	7	
GET2Examples	73	0	48	
GET2RegularTickDecorator	6	1	24	
GET2InteractionWrapper	9	1	33	
GET2LeftRightAxisStrategy	3	0	11	
GET2CompositeBuilder	6	1	31	
GET2AxisBuilderTest	16	0	124	
GET2TitleDecorator	3	0	20	
'').
b addName: ''Version 47 of GraphET2'' table: (RTTabTable new input:  ''GET2Axis	40	10	105	
GET2TopDownAxisStrategy	3	0	11	
GET2ModelLabelDecorator	5	1	27	
GET2YAxisBuilder	4	0	11	
GET2Line	10	5	49	
GET2Version	4	2	13	
GTBuilderTest	4	0	51	
GET2SingleAxisDiagram	7	2	20	
GET2HorizontalLabelCreator	1	0	7	
GET2BarDiagramTest	35	0	521	
GET2AxisBuilderTest	16	0	124	
GET2Scatterplot	5	1	53	
GET2AbstractBarDiagram	8	2	24	
GET2AxisBuilder	50	11	151	
GET2RegularTickDecorator	6	1	24	
GET2LabelCreator	6	0	7	
DotaHero	8	4	21	
GET2AbstractLineDiagram	19	5	78	
GET2InteractionWrapper	9	1	33	
GET2LineDiagram	19	3	93	
GET2OldExamples	60	0	48	
GET2DataObject	8	3	24	
GET2CompositeDiagramTest	17	0	252	
GET2Distribution	8	1	41	
GET2Table	28	2	100	
GET2XAxisBuilder	4	0	11	
GET2InteractionBuilder	4	2	25	
GET2Examples	73	0	48	
GET2ObliqueLabelCreator	6	1	15	
GET2Bar	5	1	14	
GET2VerticalLabelCreator	2	0	7	
GET2PieDiagramTest	2	0	22	
GET2LeftRightAxisStrategy	3	0	11	
GET2BackgroundLinesDecorator	11	2	42	
GET2LineDiagramTest	12	0	131	
GET2AbstractDiagram	70	16	205	
GET2AbstractAxisStrategy	8	1	17	
GET2UnionDiagram	9	1	31	
GET2UnionDiagramTest	5	0	128	
GET2HorizontalBar	2	0	15	
GET2Builder	30	12	115	
GET2OrdinaryLineDiagram	8	1	43	
GET2VerticalBar	2	0	15	
GET2PieDiagram	9	2	37	
GET2NumericLabelDecorator	18	3	92	
GET2LabelDecorator	1	0	7	
GET2CompositeBuilder	6	1	31	
GET2UnionBuilder	5	1	18	
GET2VerticalBarDiagram	8	0	65	
GET2HorizontalBarDiagram	12	0	72	
GET2AbstractAxisDecorator	20	4	88	
GET2BaseLineDecorator	2	0	10	
GET2CatalogSample	10	2	29	
GET2ScatterplotDiagram	7	1	38	
GET2Catalog	10	1	23	
GET2DiagramBuilder	21	2	59	
GET2CompositeDiagram	14	1	65	
GET2CompositeBuilderTest	11	0	150	
GET2TitleDecorator	3	0	20	
'').

b x: #second.
b y: #third.
b size: #fourth.
b open.
b view canvas '
	
"
Class {
	#name : #RTAnimatedScatterPlotExample,
	#superclass : #RTAbstractExample,
	#category : #'Roassal2-Builder-AnimatedScatterPlot'
}

{ #category : #'as yet unclassified' }
RTAnimatedScatterPlotExample >> exampleEvolutionOfGraphET2 [

| b |
b := RTAnimatedScatterPlot new.

b addName: 'Version 22 of GraphET2' table: (RTTabTable new input:  'GET2HorizontalBarDiagram	12	0	70	
GET2AbstractLineDiagram	23	5	86	
GET2AxisBuilderTest	8	0	54	
GET2UnionDiagram	8	1	26	
GET2VerticalLabelDecorator	3	0	10	
GET2RegularLabelDecorator	12	2	51	
GET2ModelLabelDecorator	8	2	31	
GTScatterplot	5	1	51	
GET2AbstractAxisBuilder	18	2	55	
GET2Abstract2DDiagram	22	4	94	
GET2SingleAxisDiagram	17	2	65	
GET2Examples	64	0	48	
GET2RegularTickDecorator	6	1	24	
GET2AbstractAxisDecorator	10	1	64	
GET2AbstractAxisStrategy	8	1	17	
GET2OrdinaryLineDiagram	7	1	40	
GET2TopDownAxisStrategy	3	0	11	
GET2AbstractBarDiagram	11	2	34	
GET2Distribution	8	1	41	
GET2InteractionWrapper	9	1	33	
GET2UnionDiagramTest	4	0	60	
GTBuilderTest	3	0	38	
GTHistogram	2	0	5	
GET2BaseLineDecorator	2	0	10	
GTAbstractBuilder	18	4	57	
GTLine	3	0	19	
GET2LineDiagram	19	3	94	
GET2DiagramBuilder	19	2	55	
GET2PieDiagramTest	2	0	22	
GET2YAxisBuilder	2	0	15	
GET2Scatterplot	7	1	38	
GET2PieDiagram	9	2	35	
GET2OldExamples	59	0	48	
GET2XAxisBuilder	2	0	15	
GET2LineDiagramTest	12	0	128	
GET2CompositeDiagramTest	16	0	240	
GET2VerticalBarDiagram	11	0	66	
GET2BarDiagramTest	34	0	525	
GET2AbstractDiagram	47	15	138	
GET2TitleDecorator	2	0	14	
GET2CompositeDiagram	18	1	70	
GET2RotatedLabelDecorator	10	1	47	
GET2Axis	29	10	71	
GET2Version	4	2	13	
DotaHero	8	4	21	
GET2LeftRightAxisStrategy	3	0	11	
GET2DataObject	8	3	24	
').

b addName: 'Version 28 of GraphET2' table: (RTTabTable new input: 
'GET2HorizontalBarDiagram	12	0	71	
GET2AbstractLineDiagram	21	5	82	
GET2VerticalLabelDecorator	3	0	10	
GET2UnionDiagram	8	1	26	
GET2AbstractBuilder	26	11	85	
GET2RegularLabelDecorator	12	2	51	
GET2ModelLabelDecorator	8	2	31	
GET2CatalogTest	1	0	10	
GET2AbstractAxisBuilder	29	4	85	
GET2SingleAxisDiagram	11	2	38	
GET2Examples	69	0	48	
GET2AbstractAxisBuilderTest	11	0	80	
GET2RegularTickDecorator	6	1	24	
GET2Line	10	5	44	
GET2CatalogSample	10	2	29	
GET2AbstractAxisDecorator	11	1	66	
GET2AbstractAxisStrategy	8	1	17	
GET2OrdinaryLineDiagram	8	1	43	
GET2TopDownAxisStrategy	3	0	11	
GET2AbstractBarDiagram	8	2	24	
GET2InteractionBuilder	4	2	25	
GET2Distribution	8	1	41	
GET2InteractionWrapper	9	1	33	
GET2UnionDiagramTest	4	0	60	
GTBuilderTest	3	0	38	
GET2ScatterplotDiagram	7	1	38	
GET2BaseLineDecorator	2	0	10	
GET2LineDiagram	17	3	85	
GET2DiagramBuilder	19	2	55	
GET2PieDiagramTest	2	0	22	
GET2YAxisBuilder	4	0	11	
GET2Scatterplot	5	1	51	
GET2PieDiagram	9	2	35	
GET2OldExamples	59	0	48	
GET2XAxisBuilder	4	0	11	
GET2LineDiagramTest	12	0	128	
GET2Catalog	10	1	23	
GET2CompositeDiagramTest	16	0	240	
GET2Histogram	10	2	31	
GET2VerticalBarDiagram	10	0	67	
GET2BarDiagramTest	34	0	525	
GET2AbstractDiagram	54	15	156	
GET2TitleDecorator	2	0	14	
GET2CompositeDiagram	16	1	66	
GET2RotatedLabelDecorator	10	1	47	
GET2Axis	33	10	85	
GET2Version	4	2	13	
DotaHero	8	4	21	
GET2LeftRightAxisStrategy	3	0	11	
GET2DataObject	8	3	24	
').


b addName: 'Version 34 of GraphET2' table: (RTTabTable new input: 
'GET2CompositeBuilder	7	1	31	
GET2HorizontalBarDiagram	12	0	72	
GET2Builder	29	11	95	
GET2AbstractLineDiagram	19	5	78	
GET2Bar	10	2	31	
GET2UnionDiagram	9	1	29	
GET2VerticalLabelDecorator	3	0	10	
GET2RegularLabelDecorator	12	2	51	
GET2ModelLabelDecorator	8	2	32	
GET2CatalogTest	1	0	10	
GET2LabelDecorator	8	0	48	
GET2SingleAxisDiagram	7	2	20	
GET2Examples	73	0	48	
GET2RegularTickDecorator	6	1	24	
GET2Line	10	5	44	
GET2CatalogSample	10	2	29	
GET2AbstractAxisDecorator	9	2	38	
GET2AbstractAxisStrategy	8	1	17	
GET2OrdinaryLineDiagram	8	1	43	
GET2TopDownAxisStrategy	3	0	11	
GET2AbstractBarDiagram	8	2	24	
GET2InteractionBuilder	4	2	25	
GET2Distribution	8	1	41	
GET2InteractionWrapper	9	1	33	
GET2UnionDiagramTest	4	0	60	
GTBuilderTest	3	0	38	
GET2UnionBuilder	5	1	17	
GET2AxisBuilder	39	7	109	
GET2AxisBuilderTest	15	0	119	
GET2LineDiagram	19	3	93	
GET2BaseLineDecorator	2	0	10	
GET2ScatterplotDiagram	7	1	38	
GET2PieDiagramTest	2	0	22	
GET2YAxisBuilder	4	0	11	
GET2Scatterplot	5	1	52	
GET2PieDiagram	9	2	37	
GET2OldExamples	60	0	48	
GET2XAxisBuilder	4	0	11	
GET2DiagramBuilder	19	2	55	
GET2LineDiagramTest	12	0	128	
GET2Catalog	10	1	23	
GET2CompositeDiagramTest	16	0	240	
GET2VerticalBarDiagram	8	0	64	
GET2BarDiagramTest	34	0	525	
GET2AbstractDiagram	67	15	193	
GET2TitleDecorator	2	0	14	
GET2CompositeDiagram	14	1	62	
GET2RotatedLabelDecorator	6	1	18	
GET2Axis	36	10	91	
GET2Version	4	2	13	
DotaHero	8	4	21	
GET2LeftRightAxisStrategy	3	0	11	
GET2DataObject	8	3	24	
').


b addName: 'Version 38 of GraphET2' table: (RTTabTable new input:  'GET2LabelDecorator	1	1	7	
GET2VerticalBarDiagram	8	0	65	
GET2SingleAxisDiagram	7	2	20	
GET2PieDiagram	9	2	37	
GET2HorizontalBarDiagram	12	0	72	
GET2Line	10	5	44	
GET2NumericLabelDecorator	15	3	55	
GET2Axis	38	10	99	
DotaHero	8	4	21	
GET2LineDiagram	19	3	93	
GET2TopDownAxisStrategy	3	0	11	
GET2Scatterplot	5	1	52	
GET2XAxisBuilder	4	0	11	
GTBuilderTest	3	0	38	
GET2Bar	10	2	31	
GET2UnionDiagramTest	5	0	128	
GET2AbstractLineDiagram	19	5	78	
GET2DiagramBuilder	21	2	59	
GET2InteractionBuilder	4	2	25	
GET2AbstractBarDiagram	8	2	24	
GET2AbstractAxisDecorator	19	2	84	
GET2ObliqueLabelCreator	6	1	15	
GET2HorizontalLabelCreator	1	0	7	
GET2VerticalLabelCreator	2	0	7	
GET2Version	4	2	13	
GET2OldExamples	60	0	48	
GET2BaseLineDecorator	2	0	10	
GET2PieDiagramTest	2	0	22	
GET2LineDiagramTest	12	0	131	
GET2Catalog	10	1	23	
GET2ModelLabelDecorator	8	2	33	
GET2DataObject	8	3	24	
GET2UnionDiagram	9	1	31	
GET2BarDiagramTest	35	0	521	
GET2OrdinaryLineDiagram	8	1	43	
GET2ScatterplotDiagram	7	1	38	
GET2Builder	32	12	104	
GET2Distribution	8	1	41	
GET2AbstractAxisStrategy	8	1	17	
GET2CatalogSample	10	2	29	
GET2CompositeDiagram	14	1	64	
GET2AxisBuilder	45	9	137	
GET2YAxisBuilder	4	0	11	
GET2CompositeDiagramTest	16	0	240	
GET2AbstractDiagram	69	16	202	
GET2UnionBuilder	5	1	17	
GET2LabelCreator	6	0	7	
GET2Examples	72	0	48	
GET2RegularTickDecorator	7	1	30	
GET2InteractionWrapper	9	1	33	
GET2LeftRightAxisStrategy	3	0	11	
GET2CompositeBuilder	7	1	31	
GET2AxisBuilderTest	16	0	124	
GET2TitleDecorator	3	0	20	
').
b addName: 'Version 42 of GraphET2' table: (RTTabTable new input:  'GET2LabelDecorator	1	0	7	
GET2VerticalBarDiagram	8	0	65	
GET2SingleAxisDiagram	7	2	20	
GET2PieDiagram	9	2	37	
GET2HorizontalBarDiagram	12	0	72	
GET2Line	10	5	49	
GET2CompositeBuilderTest	11	0	150	
GET2NumericLabelDecorator	14	3	53	
GET2Axis	40	10	105	
DotaHero	8	4	21	
GET2LineDiagram	19	3	93	
GET2TopDownAxisStrategy	3	0	11	
GET2Scatterplot	5	1	53	
GET2XAxisBuilder	4	0	11	
GTBuilderTest	3	0	45	
GET2Bar	10	2	31	
GET2BackgroundLinesDecorator	11	2	42	
GET2AbstractLineDiagram	19	5	78	
GET2UnionDiagramTest	5	0	128	
GET2InteractionBuilder	4	2	25	
GET2AbstractBarDiagram	8	2	24	
GET2AbstractAxisDecorator	20	4	88	
GET2ObliqueLabelCreator	6	1	15	
GET2HorizontalLabelCreator	1	0	7	
GET2VerticalLabelCreator	2	0	7	
GET2Version	4	2	13	
GET2OldExamples	60	0	48	
GET2BaseLineDecorator	2	0	10	
GET2PieDiagramTest	2	0	22	
GET2LineDiagramTest	12	0	131	
GET2Catalog	10	1	23	
GET2DiagramBuilder	21	2	59	
GET2ModelLabelDecorator	5	1	27	
GET2DataObject	8	3	24	
GET2UnionDiagram	9	1	31	
GET2BarDiagramTest	35	0	521	
GET2OrdinaryLineDiagram	8	1	43	
GET2ScatterplotDiagram	7	1	38	
GET2Builder	30	12	112	
GET2Distribution	8	1	41	
GET2AbstractAxisStrategy	8	1	17	
GET2CatalogSample	10	2	29	
GET2CompositeDiagram	14	1	65	
GET2AxisBuilder	50	11	151	
GET2YAxisBuilder	4	0	11	
GET2CompositeDiagramTest	17	0	252	
GET2AbstractDiagram	70	16	205	
GET2UnionBuilder	5	1	18	
GET2LabelCreator	6	0	7	
GET2Examples	73	0	48	
GET2RegularTickDecorator	6	1	24	
GET2InteractionWrapper	9	1	33	
GET2LeftRightAxisStrategy	3	0	11	
GET2CompositeBuilder	6	1	31	
GET2AxisBuilderTest	16	0	124	
GET2TitleDecorator	3	0	20	
').
b addName: 'Version 45 of GraphET2' table: (RTTabTable new input:  'GET2LabelDecorator	1	0	7	
GET2VerticalBarDiagram	8	0	65	
GET2SingleAxisDiagram	7	2	20	
GET2PieDiagram	9	2	37	
GET2HorizontalBarDiagram	12	0	72	
GET2Line	10	5	49	
GET2CompositeBuilderTest	11	0	150	
GET2NumericLabelDecorator	18	3	90	
GET2Axis	40	10	105	
DotaHero	8	4	21	
GET2LineDiagram	19	3	93	
GET2TopDownAxisStrategy	3	0	11	
GET2Scatterplot	5	1	53	
GET2XAxisBuilder	4	0	11	
GTBuilderTest	3	0	45	
GET2Bar	10	2	37	
GET2BackgroundLinesDecorator	11	2	42	
GET2AbstractLineDiagram	19	5	78	
GET2UnionDiagramTest	5	0	128	
GET2InteractionBuilder	4	2	25	
GET2AbstractBarDiagram	8	2	24	
GET2AbstractAxisDecorator	20	4	88	
GET2ObliqueLabelCreator	6	1	15	
GET2HorizontalLabelCreator	1	0	7	
GET2VerticalLabelCreator	2	0	7	
GET2Version	4	2	13	
GET2OldExamples	60	0	48	
GET2BaseLineDecorator	2	0	10	
GET2PieDiagramTest	2	0	22	
GET2LineDiagramTest	12	0	131	
GET2Catalog	10	1	23	
GET2DiagramBuilder	21	2	59	
GET2ModelLabelDecorator	5	1	27	
GET2DataObject	8	3	24	
GET2UnionDiagram	9	1	31	
GET2BarDiagramTest	35	0	521	
GET2OrdinaryLineDiagram	8	1	43	
GET2ScatterplotDiagram	7	1	38	
GET2Builder	30	12	112	
GET2Distribution	8	1	41	
GET2AbstractAxisStrategy	8	1	17	
GET2CatalogSample	10	2	29	
GET2CompositeDiagram	14	1	65	
GET2AxisBuilder	50	11	151	
GET2YAxisBuilder	4	0	11	
GET2CompositeDiagramTest	17	0	252	
GET2AbstractDiagram	70	16	205	
GET2UnionBuilder	5	1	18	
GET2LabelCreator	6	0	7	
GET2Examples	73	0	48	
GET2RegularTickDecorator	6	1	24	
GET2InteractionWrapper	9	1	33	
GET2LeftRightAxisStrategy	3	0	11	
GET2CompositeBuilder	6	1	31	
GET2AxisBuilderTest	16	0	124	
GET2TitleDecorator	3	0	20	
').
b addName: 'Version 47 of GraphET2' table: (RTTabTable new input:  'GET2Axis	40	10	105	
GET2TopDownAxisStrategy	3	0	11	
GET2ModelLabelDecorator	5	1	27	
GET2YAxisBuilder	4	0	11	
GET2Line	10	5	49	
GET2Version	4	2	13	
GTBuilderTest	4	0	51	
GET2SingleAxisDiagram	7	2	20	
GET2HorizontalLabelCreator	1	0	7	
GET2BarDiagramTest	35	0	521	
GET2AxisBuilderTest	16	0	124	
GET2Scatterplot	5	1	53	
GET2AbstractBarDiagram	8	2	24	
GET2AxisBuilder	50	11	151	
GET2RegularTickDecorator	6	1	24	
GET2LabelCreator	6	0	7	
DotaHero	8	4	21	
GET2AbstractLineDiagram	19	5	78	
GET2InteractionWrapper	9	1	33	
GET2LineDiagram	19	3	93	
GET2OldExamples	60	0	48	
GET2DataObject	8	3	24	
GET2CompositeDiagramTest	17	0	252	
GET2Distribution	8	1	41	
GET2Table	28	2	100	
GET2XAxisBuilder	4	0	11	
GET2InteractionBuilder	4	2	25	
GET2Examples	73	0	48	
GET2ObliqueLabelCreator	6	1	15	
GET2Bar	5	1	14	
GET2VerticalLabelCreator	2	0	7	
GET2PieDiagramTest	2	0	22	
GET2LeftRightAxisStrategy	3	0	11	
GET2BackgroundLinesDecorator	11	2	42	
GET2LineDiagramTest	12	0	131	
GET2AbstractDiagram	70	16	205	
GET2AbstractAxisStrategy	8	1	17	
GET2UnionDiagram	9	1	31	
GET2UnionDiagramTest	5	0	128	
GET2HorizontalBar	2	0	15	
GET2Builder	30	12	115	
GET2OrdinaryLineDiagram	8	1	43	
GET2VerticalBar	2	0	15	
GET2PieDiagram	9	2	37	
GET2NumericLabelDecorator	18	3	92	
GET2LabelDecorator	1	0	7	
GET2CompositeBuilder	6	1	31	
GET2UnionBuilder	5	1	18	
GET2VerticalBarDiagram	8	0	65	
GET2HorizontalBarDiagram	12	0	72	
GET2AbstractAxisDecorator	20	4	88	
GET2BaseLineDecorator	2	0	10	
GET2CatalogSample	10	2	29	
GET2ScatterplotDiagram	7	1	38	
GET2Catalog	10	1	23	
GET2DiagramBuilder	21	2	59	
GET2CompositeDiagram	14	1	65	
GET2CompositeBuilderTest	11	0	150	
GET2TitleDecorator	3	0	20	
').

b x: #second.
b y: #third.
b size: #fourth.
b open.
b view canvas 
]

{ #category : #'as yet unclassified' }
RTAnimatedScatterPlotExample >> exampleEvolutionOfGraphET2Icon [
	^ 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABeCAYAAADVA7GfAAAEDElEQVR4XuWcXU8jVRjHH14K
lJbyUl4KDFAItGWlUFtkXSjtIltfSH3JJpJGXPVC1zUa9mYxaNxbo4l3Xph44Rfwxg/kJ9hP
sc8fnaRpClnjUpr8fpmT6cycOTN9/uc8Z+ZkzmN8+PC5iju+XJUCs4BvpQ5S9+Uds/tat0sZ
s0zLKbE2xQx34l5jsdjMi+YdGBiIB0Fwu6+vb6B5/+LiYnl4eHjSU7K3t7ev9bz5+fnbLfn3
+/v7oypL2+l0+q7WiUTieirqgdnnVbOv/Cpfenq4bvZHweyXW2a/F81+WjPLNWU/t3+2m0V5
xdN3nuLXLcjo6OhSoVD4rF6v/7a1tfVpNBqd2NnZ+XpjY6Oxvr5+f3Nz86RarT6dnZ0tefae
mZmZrVQq9arO3dvbO5uYmFjLZrPvVyqVH7RP+ebm5l7zY9/m8/mPlGd7e/uRG/3AxYoo7e/v
f6+8XvYDrXd3d5/0OAsLC7u65kv/kxWzb940a7xl9uE9swdls8fuqs5dnEc1s5MWQW6UpaWl
ajweT8kY09PTG6q5q6urb+v38vLygY5PTk7mxsfHV5QnEonEfP8bbr9eN35R57qoi2o1XvP3
tE/lJpPJNQmissLzVfbg4GBCLaS5dfo1Ki7OxxduwVvaS/+TcklXpaTfL8F1y8XxOzA+fPjw
4cOHDx8+fPjw4cOnm/ChldmRkZF5viW6hFKp9FBJg5Z8a3QBmUym7qPB7/EtwYcPHz58+PDh
w4cPHz58+PABoa8Mh4aGxviW6BI0YLiysnKPb4kuQUPq/BbChw8fPkzSFwufruHuxcKHLwgf
viB8QfjwBeELwudmBdGETc2wjUQiUb71ukAQza7VgGI4y5YP32WxBNFc8nbD6fl8/kStQkEF
1EL4luuQIJrQ3y7MRjKZzCo4gMJnKBoD33IdEkQhL9pN9Nd0giAIXudbrMOCyC3pS/U2nXlJ
rkrC8K3WBZ26Ypu428rwLdYhQVTzw6RgMblc7gOtdSyVShVqtdrPigzEt9gNCOIu611F5gk7
70QisSBxFP2Hb7HOuqye5qet5nz6kEGhmPgW65AgU1NTtw4PD388PT39++zs7Fmj0firOd+/
b+eldmXoqUytSnmKxeIXalF8y15TC9E7iT/u3lEgs8taiEQIJ3WGif8A8D8E0Zv50dHRr3pL
lyF9u1apVJ4eHx//WS6Xz0Mjt6v5iiLXKoaSv9F/8qL3oL7JhZ/Wb8Vd9MowihblPwgSXJMg
h02CHOAFuQzFPRwbG0vLZSno5WX5LnFZWb4Fb4jwUTns1PXewrcKHz58+PDhw4cPHz58+PDh
w4cPHz58+PDhw4cPHz58+PDhw4cPHz58+PDhw4cPHz58+PDhw4cPHz58+PAB8xxBI6zg3zwY
igAAAABJRU5ErkJggg=='
]

{ #category : #'as yet unclassified' }
RTAnimatedScatterPlotExample >> exampleSimple [

| b t1 t2 t3 |

t1 := RTTabTable new input: '
	m1	m2	m3
A	1	2	1
B	2	5	4
C	1	7	4	'.
t1 removeFirstRow.

t2 := RTTabTable new input: '
	m1	m2	m3
A	1	4	8
B	2	6	4
C	1	6	2	'.
t2 removeFirstRow.

t3 := RTTabTable new input: '
	m1	m2	m3
A	2	5	5
B	2	5	4
C	2	7	8	'.
t3 removeFirstRow.

b := RTAnimatedScatterPlot new.
b addTable: t1.
b addTable: t2.
b addTable: t3.
b x: #second.
b y: #third.
b size: #fourth.
b open.
b view canvas 
]

{ #category : #'as yet unclassified' }
RTAnimatedScatterPlotExample >> exampleSimpleIcon [
	^ 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABjCAYAAABt56XsAAABy0lEQVR4XuXbMUsbcRzH4V/k
gkkMQXJCCFgQQs4l1JI4dDMttIoWN2kHJ1H7Hpzt1kXfgm+0/xsOLErIIMnh85A/ZEmG74fc
JUPC5/Mt8iM9Fp08IvdXWqGvEVefIv4uGWTrlbfo+Cu+oS8R1ycRF/sRT4cRf+YRtx8jHs4i
ztPz38+CHKVzkc782cv30kk949Jf8o2kCPdFivE54u5bGjbFeKw+HccRv/xL1oqVgy86WUTm
r+Tz+Xw+n8/n8/l8Pp/P5/P5fD6fz+fz+Xw+n8/n8/l8Pp/P5/P5fD6fz+fzvSPz//9G90Kv
1/vQ7XaH/lI1CJLneTGbzW7LU4bx11pzkMlk8rMKMh6PT/211hwkfSp2qyD+Zasm95Asy9rp
bPpL1STIMvr9/rjZbG75a9YgSLq3nFWXtU6ns+MvuuYgVYzyDIfDmb/omoOMRqPvZYzpdHrT
arW2/UVrcA9pt9t5o9HY8NesSRCfH8QP4vOD+EFeUxTFefomdewvVZMgg8HgoPwl7i/lX7L8
ID4/iM8P4vP5fD6fz+fz+Xw+n8/n8/l8Pp/P5/P5fD6fz+fz+Xw+n8/n8/l8Pp/P5/P5fD6f
z+fz+Xw+33L+AUWxN2Nrk18AAAAAAElFTkSuQmCC'
]

{ #category : #'as yet unclassified' }
RTAnimatedScatterPlotExample >> label [
	^ 'Animated scatter plot'
]
