Class {
	#name : #RTPalette,
	#superclass : #RTObject,
	#category : #'Roassal2-ColorNormalizer'
}

{ #category : #palettes }
RTPalette class >> c1 [
	^ Array 
		with: (Color red: 225 green: 206 blue: 122) 
		with: (Color red: 251 green: 255 blue: 185)
		with: (Color red: 253 green: 214 blue: 146)
		with: (Color red: 236 green: 115 blue: 87)
		with: (Color red: 117 green: 79 blue: 68)
]

{ #category : #palettes }
RTPalette class >> c10 [
	^ Array
		with: (Color red: 51 green: 92 blue: 103)
		with: (Color red: 255 green: 243 blue: 176)
		with: (Color red: 224 green: 159 blue: 62)
		with: (Color red: 158 green: 42 blue: 43)
		with: (Color red: 84 green: 11 blue: 14)
]

{ #category : #palettes }
RTPalette class >> c11 [
	^ Array
		with: (Color red: 30 green: 21 blue: 42)
		with: (Color red: 78 green: 103 blue: 102)
		with: (Color red: 90 green: 177 blue: 187)
		with: (Color red: 165 green: 200 blue: 130)
		with: (Color red: 247 green: 221 blue: 114)
]

{ #category : #palettes }
RTPalette class >> c12 [
	^ Array
		with: (Color red: 204 green: 88 blue: 3)
		with: (Color red: 226 green: 113 blue: 29)
		with: (Color red: 255 green: 149 blue: 5)
		with: (Color red: 255 green: 182 blue: 39)
		with: (Color red: 255 green: 201 blue: 113)
]

{ #category : #palettes }
RTPalette class >> c13 [
	^ Array
		with: (Color red: 123 green: 223 blue: 242)
		with: (Color red: 178 green: 247 blue: 239)
		with: (Color red: 239 green: 247 blue: 246)
		with: (Color red: 247 green: 214 blue: 224)
		with: (Color red: 242 green: 181 blue: 212)
]

{ #category : #palettes }
RTPalette class >> c14 [
	^ Array
		with: (Color red: 254 green: 147 blue: 140)
		with: (Color red: 237 green: 175 blue: 151)
		with: (Color red: 196 green: 151 blue: 146)
		with: (Color red: 173 green: 145 blue: 163)
		with: (Color red: 157 green: 145 blue: 163)
]

{ #category : #palettes }
RTPalette class >> c2 [
	^ Array
		with: (Color red: 58 green: 96 blue: 110)
		with: (Color red: 96 green: 123 blue: 125)
		with: (Color red: 130 green: 142 blue: 130)
		with: (Color red: 170 green: 174 blue: 142)
		with: (Color red: 224 green: 224 blue: 224)
]

{ #category : #palettes }
RTPalette class >> c3 [
	^ Array
		with: (Color red: 239 green: 217 blue: 206)
		with: (Color red: 222 green: 192 blue: 241)
		with: (Color red: 183 green: 156 blue: 237)
		with: (Color red: 149 green: 127 blue: 239)
		with: (Color red: 113 green: 97 blue: 239)
]

{ #category : #palettes }
RTPalette class >> c4 [
	^ Array
		with: (Color red: 36 green: 123 blue: 160)
		with: (Color red: 112 green: 193 blue: 179)
		with: (Color red: 178 green: 219 blue: 191)
		with: (Color red: 243 green: 255 blue: 189)
		with: (Color red: 255 green: 22 blue: 84)
]

{ #category : #palettes }
RTPalette class >> c5 [
	^ Array
		with: (Color red: 220 green: 220 blue: 221)
		with: (Color red: 197 green: 195 blue: 198)
		with: (Color red: 70 green: 73 blue: 76)
		with: (Color red: 76 green: 92 blue: 104)
		with: (Color red: 25 green: 133 blue: 161)
]

{ #category : #palettes }
RTPalette class >> c6 [
	^ Array
		with: (Color red: 216 green: 226 blue: 220)
		with: (Color red: 255 green: 229 blue: 217)
		with: (Color red: 255 green: 202 blue: 212)
		with: (Color red: 244 green: 172 blue: 183)
		with: (Color red: 157 green: 129 blue: 137)
]

{ #category : #palettes }
RTPalette class >> c7 [
	^ Array
		with: (Color red: 224 green: 251 blue: 252)
		with: (Color red: 194 green: 223 blue: 227)
		with: (Color red: 157 green: 180 blue: 192)
		with: (Color red: 92 green: 107 blue: 115)
		with: (Color red: 37 green: 50 blue: 55)
]

{ #category : #palettes }
RTPalette class >> c8 [
	^ Array
		with: (Color red: 151 green: 249 blue: 249)
		with: (Color red: 164 green: 222 blue: 249)
		with: (Color red: 193 green: 224 blue: 247)
		with: (Color red: 207 green: 186 blue: 225)
		with: (Color red: 197 green: 159 blue: 201)
]

{ #category : #palettes }
RTPalette class >> c9 [
	^ Array
		with: (Color red: 237 green: 238 blue: 201)
		with: (Color red: 221 green: 231 blue: 199)
		with: (Color red: 191 green: 216 blue: 189)
		with: (Color red: 152 green: 201 blue: 163)
		with: (Color red: 119 green: 191 blue: 163)
]
