"
I am an point with an offset
"
Class {
	#name : #RTXPPoint,
	#superclass : #Point,
	#instVars : [
		'y0'
	],
	#category : #'Roassal2-Experimental'
}

{ #category : #'as yet unclassified' }
RTXPPoint >> x: aNumber [
	x := aNumber
]

{ #category : #'as yet unclassified' }
RTXPPoint >> y0 [
	^ y0
]

{ #category : #'as yet unclassified' }
RTXPPoint >> y0: aNumber [
	y0 := aNumber
]

{ #category : #'as yet unclassified' }
RTXPPoint >> y: aNumber [
	y := aNumber
]
